name: solar
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.2
  - apipkg=1.5
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - blas=2.8
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - certifi=2019.3.9
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cycler=0.10.0
  - execnet=1.6.0
  - expat=2.2.5
  - ffmpeg=4.1.1
  - fire=0.1.3
  - fontconfig=2.13.1
  - freexl=1.0.5
  - geos=3.7.1
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - jasper=1.900.1
  - jpeg=9c
  - json-c=0.13.1
  - kealib=1.4.10
  - kiwisolver=1.0.1
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libdap4=3.19.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.2
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libwebp=1.0.2
  - libxml2=2.9.8
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.4
  - more-itertools=4.3.0
  - mypy=0.701
  - mypy_extensions=0.4.1
  - nettle=3.4.1
  - openblas=0.3.6
  - openh264=1.8.0
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - pandas=0.24.2
  - pcre=8.41
  - pep8=1.7.1
  - pixman=0.34.0
  - pluggy=0.9.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - psutil=5.4.8
  - py=1.8.0
  - pyparsing=2.4.0
  - pytest=4.4.0
  - pytest-pep8=1.0.6
  - python-dateutil=2.8.0
  - pytz=2018.9
  - rasterio=1.0.22
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - snuggs=1.4.3
  - tornado=6.0.2
  - tqdm=4.31.1
  - typed-ast=1.3.5
  - x264=1!152.20180806
  - xerces-c=3.2.2
  - cffi=1.12.2
  - curl=7.64.0
  - freetype=2.9.1
  - intel-openmp=2019.3
  - krb5=1.16.1
  - libcurl=7.64.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libopenblas=0.3.3
  - libpng=1.6.36
  - libpq=11.2
  - libtiff=4.0.10
  - mkl=2019.3
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - pillow=5.4.1
  - pip=19.0.3
  - postgresql=11.2
  - pycparser=2.19
  - pytest-cache=1.0
  - python=3.7.3
  - readline=7.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.0.1
  - torchvision=0.2.2
  - pip:
    - torch==1.0.1.post2
